Homepage/urls.py
from django.urls import path
from .views import Home, Login, Register, Logout, GetUsers, Profile, GetDrives, Drive, UpdateDrive, DeleteDrive, NewDrive, ApplyDrive, DriveResponses, NewCoordinator, Coordinators

from .views import AddDepartment, GetDepartments, AddCourse, GetCourses, AddCompanies, GetCompanies, AddAnnouncement, GetAnnouncements

urlpatterns = [
    # 404 ERROR PAGE
    # path('ERROR', Error.as_view(), name="error"),

    path('', Home.as_view(), name="homepage"),

    # USER AUTHENTICATION & REGISTRATION
    path('login/', Login.as_view(), name="login"),
    path('register/', Register.as_view(), name="register"),
    path('logout/', Logout.as_view(), name="logout"),

    path('users/', GetUsers.as_view(), name="users"),
    path('profile/<str:id>/', Profile.as_view(), name="profile"),
    # path('user/', GetUsers.as_view(), name="users"),
    
    path('drives/', GetDrives.as_view(), name="drives"),
    path('drives/<int:id>/', Drive.as_view(), name="drive"),
    path('drives/<int:id>/apply/', ApplyDrive.as_view(), name='apply_drive'),
    path('drives/<int:id>/update/', UpdateDrive.as_view(), name="update_drive"),
    path('drives/<int:id>/delete/', DeleteDrive.as_view(), name="delete_drive"),
    path('drives/<int:id>/responses/', DriveResponses.as_view(), name="drive_responses"),
    path('newdrive/', NewDrive.as_view(), name="create_drive"),
    path('applydrive/<int:id>', ApplyDrive.as_view(), name='apply_drive'),

    path('newcoordinator/', NewCoordinator.as_view(), name="create_coordinator"),
    path('coordinators/', Coordinators.as_view(), name="coordinators"),

    path('departments/add/', AddDepartment.as_view(), name="add_departments"),
    path('departments/list/', GetDepartments.as_view(), name="list_departments"),

    path('courses/add/', AddCourse.as_view(), name="add_courses"),
    path('courses/list/', GetCourses.as_view(), name="list_courses"),

    path('companies/add/', AddCompanies.as_view(), name="add_companies"),
    path('companies/list/', GetCompanies.as_view(), name="list_companies"),

    
    path('announcements/add/', AddAnnouncement.as_view(), name="add_announcements"),
    path('announcements/list/', GetAnnouncements.as_view(), name="list_announcements"),
]

UPMS/Homepage/urls.py
from django.urls import path
from .views import Home, Login, Register, Logout, GetUsers, Profile, GetDrives, Drive, UpdateDrive, DeleteDrive, NewDrive, ApplyDrive, DriveResponses, NewCoordinator, Coordinators

from .views import AddDepartment, GetDepartments, AddCourse, GetCourses, AddCompanies, GetCompanies, AddAnnouncement, GetAnnouncements

urlpatterns = [
    # 404 ERROR PAGE
    # path('ERROR', Error.as_view(), name="error"),

    path('', Home.as_view(), name="homepage"),

    # USER AUTHENTICATION & REGISTRATION
    path('login/', Login.as_view(), name="login"),
    path('register/', Register.as_view(), name="register"),
    path('logout/', Logout.as_view(), name="logout"),

    path('users/', GetUsers.as_view(), name="users"),
    path('profile/<str:id>/', Profile.as_view(), name="profile"),
    # path('user/', GetUsers.as_view(), name="users"),
    
    path('drives/', GetDrives.as_view(), name="drives"),
    path('drives/<int:id>/', Drive.as_view(), name="drive"),
    path('drives/<int:id>/apply/', ApplyDrive.as_view(), name='apply_drive'),
    path('drives/<int:id>/update/', UpdateDrive.as_view(), name="update_drive"),
    path('drives/<int:id>/delete/', DeleteDrive.as_view(), name="delete_drive"),
    path('drives/<int:id>/responses/', DriveResponses.as_view(), name="drive_responses"),
    path('newdrive/', NewDrive.as_view(), name="create_drive"),
    path('applydrive/<int:id>', ApplyDrive.as_view(), name='apply_drive'),

    path('newcoordinator/', NewCoordinator.as_view(), name="create_coordinator"),
    path('coordinators/', Coordinators.as_view(), name="coordinators"),

    path('departments/add/', AddDepartment.as_view(), name="add_departments"),
    path('departments/list/', GetDepartments.as_view(), name="list_departments"),

    path('courses/add/', AddCourse.as_view(), name="add_courses"),
    path('courses/list/', GetCourses.as_view(), name="list_courses"),

    path('companies/add/', AddCompanies.as_view(), name="add_companies"),
    path('companies/list/', GetCompanies.as_view(), name="list_companies"),

    
    path('announcements/add/', AddAnnouncement.as_view(), name="add_announcements"),
    path('announcements/list/', GetAnnouncements.as_view(), name="list_announcements"),
]

UPMS/UPMS/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from Homepage import views

urlpatterns = [
    path('', include('Homepage.urls')),
    path('admin/', admin.site.urls),
    path('api/', views.ChartData.as_view()),
    path('api/PlacedUnplaced/', views.PlacedUnplaced.as_view()),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UPMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

from Homepage import views

urlpatterns = [
    path('', include('Homepage.urls')),
    path('admin/', admin.site.urls),
    path('api/', views.ChartData.as_view()),
    path('api/PlacedUnplaced/', views.PlacedUnplaced.as_view()),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Homepage/models.py
from datetime import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Departments(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Departments'
        verbose_name_plural = 'Departments'


class Course(models.Model):
    name = models.CharField(max_length=256)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Courses'
        verbose_name_plural = 'Courses'


class Companies(models.Model):
    name = models.CharField(max_length=256)
    about = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Companies'
        verbose_name_plural = 'Companies'


class User(AbstractUser):
    email = models.EmailField(max_length=256, unique=True)
    GENDER = (
        (1,'Male'),
        (2,'Female'),
        (3,'Other')
    )
    
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)

    dob = models.DateField(null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER, null=True, blank=True)
    mobile = models.CharField(max_length=20, null=True, blank=True, unique=True)
    whatsapp = models.CharField(max_length = 20, null=True, blank=True, unique=True)
    
    address = models.TextField(help_text = "Enter address")
    city = models.CharField(max_length=50, help_text = "Enter City")
    pincode = models.CharField(max_length=6, help_text = "Enter pincode")
    state = models.CharField(max_length=50, help_text = "Enter state")

    ssc = models.CharField(max_length=128, null=True, blank=True)
    ssc_year = models.PositiveSmallIntegerField(null=True, blank=True)
    ssc_percentage = models.PositiveSmallIntegerField(null=True, blank=True)
    ssc_cgpa = models.FloatField(null=True, blank=True)

    hssc = models.CharField(max_length=128, null=True, blank=True)
    hssc_year = models.PositiveSmallIntegerField(null=True, blank=True)
    hssc_percentage = models.PositiveSmallIntegerField(null=True, blank=True)
    hssc_cgpa = models.FloatField(null=True, blank=True)

    ug = models.CharField(max_length=128, null=True, blank=True)
    ug_year = models.PositiveSmallIntegerField(null=True, blank=True)
    ug_percentage = models.PositiveSmallIntegerField(null=True, blank=True)
    ug_cgpa = models.FloatField(null=True, blank=True)

    pg = models.CharField(max_length=128, null=True, blank=True)
    pg_year = models.PositiveSmallIntegerField(null=True, blank=True)
    pg_percentage = models.PositiveSmallIntegerField(null=True, blank=True)
    pg_cgpa = models.FloatField(null=True, blank=True)


    department_name = models.ForeignKey(Departments, blank=True, null=True, on_delete=models.CASCADE, related_name='department_name')
    course_name = models.ForeignKey(Course, blank=True, null=True, on_delete=models.CASCADE)
    placed_in = models.ManyToManyField(Companies, blank=True, related_name='placed_in')
    salary = models.FloatField(null=True, blank=True)
    
    is_student = models.BooleanField(default=False)
    is_coordinator = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_placed = models.BooleanField(default=False)


    date_joined = models.DateTimeField(verbose_name='date joined', default=timezone.now)
    last_login = models.DateTimeField(verbose_name='last login', default=timezone.now)
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def __str__(self):
        return '%s %s (%s)' % (self.first_name, self.last_name, self.username)
    
    class Meta:
        verbose_name = 'Users'
        verbose_name_plural = 'Users'


class Drives(models.Model):
    name = models.CharField(max_length=256, help_text = "Drive name")
    DRIVE_TYPE = (
        (1,'Virtual'),
        (2,'On Campus'),
        (3,'Off Campus')
    )
    drive_type = models.PositiveSmallIntegerField(choices=DRIVE_TYPE, help_text ="Enter type of drive")
    created = models.DateTimeField(default = timezone.now)
    drive_on = models.DateField(help_text="Enter in the following format : YYYY-MM-DD")
    STREAMS = (
        (1,'MCA'),
        (2,'BCA'),
        (3,'B Tech')
    )
    stream_required = models.PositiveSmallIntegerField(choices=STREAMS)
    batch_year = models.IntegerField(('year'), default=datetime.now().year)
    eligibility = models.IntegerField(blank=True)
    position = models.CharField(max_length=255, blank=True)
    job_profile = models.CharField(max_length=255, blank=True)
    JOB_TYPE_CHOICE = (
        (1,'WFH'),
        (2,'Full Time'),
        (3,'Internship')
    )
    job_type = models.PositiveSmallIntegerField(choices=JOB_TYPE_CHOICE)
    job_location = models.CharField(max_length=255, blank=True)
    date_of_joining = models.DateField()
    stipend_package = models.CharField(max_length=255, blank=True)


    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Drives'
        verbose_name_plural = 'Drives'


class Responses(models.Model):
    drive = models.ForeignKey(Drives, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    STATUS_TITLE = (
        (1,'Applied'),
        (2,'Processing'),
        (3,'Shortlisted'),
        (4,'Rejected'),
        (5,'Selected')
    )
    status = models.PositiveSmallIntegerField(choices=STATUS_TITLE, null=True, blank=True)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s-%s' % (self.user.username, self.drive.name)

    class Meta:
        verbose_name = 'Responses'
        verbose_name_plural = 'Responses'


class Announcements(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Announcements'
        verbose_name_plural = 'Announcements'

Homepage/forms.py
from dataclasses import fields
from unicodedata import name
from django import forms

from .models import Drives

class DriveForm(forms.ModelForm):

    class Meta:
        model = Drives
        fields = '__all__'

UPMS/Homepage/forms.py
from dataclasses import fields
from unicodedata import name
from django import forms

from .models import Drives

class DriveForm(forms.ModelForm):

    class Meta:
        model = Drives
        fields = '__all__'

UPMS/Homepage/templates/Drives/drive.html
{% extends 'base.html' %}
{% load static %}


{% block title %}HomePage{% endblock %}

{% block nav_sidebar %}
  {% include 'new_sidebar.html' with active="drives" %}
{% endblock %}

{% block stylesheets %}
  {% include 'adminlte/lib/_styles.html' %}
  <style>
    @media (max-width : 1000px) {
      .apply-btn {
        width: 50% !important;
      }
    }
    .apply-btn {
      width: 25%
    }
  </style>
  <link rel="stylesheet" href="{% static '/css/loader.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-12">
          <div class="card">

              <div class="card-header text-center bg-red"><h2>Apply to {{drive_data.name}}</h2></div>

              <div class="card-body p-5">

                <hr style="background: #E9ECEF; border: 1px solid #343948; width: 80%;">
                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Unique Drive ID:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.id}}</a>
                  </div>
                </div>
              
                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Name of company:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.name}}</a>
                  </div>
                </div>

                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Date of drive:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.drive_on}}</a>
                  </div>
                </div>

                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Type of drive:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.get_drive_type_display}}</a>
                  </div>
                </div>

                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Batch year:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.batch_year}}</a>
                  </div>
                </div>

                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Required streams:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.get_stream_required_display}}</a>
                  </div>
                </div>

                <div class="row py-2">
                  <div class="col-md-6">
                    <b style="font-size: 25px">Eligibility:</b> 
                  </div>
                  
                  <div class="col-md-6">
                    <a style="font-size: 25px;">{{drive_data.eligibility}}</a>
                  </div>
                </div>
                
                <hr style="background: #E9ECEF; border: 1px solid #343948; width: 80%;">

                {% if request.user.is_student %}
                <div class="text-center">
                  <a href="{% url 'apply_drive' drive_data.id %}" class="btn apply-btn btn-lg btn-success">Apply</a>
                </div>
                {% elif request.user.is_superuser or request.user.is_coordinator %}
                <div class="text-center">
                  <a href="{% url 'apply_drive' drive_data.id %}" class="btn btn-lg btn-success">Apply</a>
                  <a href="{% url 'drive_responses' drive_data.id %}" class="btn btn-lg btn-success">Responses</a>
                  <a href="{% url 'update_drive' drive_data.id %}" class="btn btn-lg btn-success">Manage Drive</a>
                  <a href="{% url 'delete_drive' drive_data.id %}" class="btn btn-lg btn-danger">Delete Drive</a>
                </div>
                {% endif %}

             </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

UPMS/Homepage/templates/Drives/drives.html
{% extends 'base.html' %}

{% block title %}Drives{% endblock %}

{% block nav_sidebar %}
  {% include 'new_sidebar.html' with active="drives" %}
{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-12">
          <div class="card">

              <div class="card-header text-center bg-red"><h2>Drives</h2></div>

              <div class="card-body text-center" style="overflow-x:auto;">
                <table class="table table-inline table-hover" style="font-size: 20px;">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Name of drive</th>
                      <th>Type of drive</th>
                      <th>Date of drive</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in drives %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td><a class="a" href="{% url 'drive' i.id %}">{{i.name}}</a></td>
                      <td>{{i.get_drive_type_display}}</td>
                      <td>{{i.drive_on}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
             </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

UPMS/Homepage/templates/Drives/new_drive.html
{% extends 'base.html' %}

{% block title %}Drive{% endblock %}

{% block nav_sidebar %}
  {% include 'new_sidebar.html' with active="create_drive" %}
{% endblock %}

{% block content %}

<div class="cotainer">
  <div class="row justify-content-center">
      <div class="col-md-10">
          <div class="card">

              <div class="card-header text-center bg-red"><h2>Add Drive</h2></div>
              
              <form method="POST" action = "{% url 'create_drive' %}">
                  {% csrf_token %}
                  <div class="card-body">
                      <div class="form-group row">
                          <label for="name" class="col-md-4 col-form-label text-md-right">Name of Company:</label>
                          <div class="col-md-6">
                              <input type="text" id="name" name="name" class="form-control" required>
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="drive_type" class="col-md-4 col-form-label text-md-right">Drive Type:</label>
                          <div class="col-md-6">
                              <select required class="form-select" id="drive_type" name="drive_type" required>
                                <option value="1">Virtual</option>
                                <option value="2">On Campus</option>
                                <option value="3">Off Campus</option>
                              </select>
                          </div>
                      </div>
                      

                      <div class="form-group row">
                          <label for="drive_on" class="col-md-4 col-form-label text-md-right">Drive Date:</label>
                          <div class="col-md-6">
                              <input type="date" id="drive_on" name="drive_on" class="form-control" required>
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="stream_required" class="col-md-4 col-form-label text-md-right">Drive For:</label>
                          <div class="col-md-6">
                              <select required class="form-select" id="stream_required" name="stream_required" required>
                                <option value="1">MCA</option>
                                <option value="2">BCA</option>
                                <option value="3">B Tech</option>
                              </select>
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="batch_year" class="col-md-4 col-form-label text-md-right">Batch Year:</label>
                          <div class="col-md-6">
                              <input type="number" id="batch_year" name="batch_year" class="form-control">
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="eligibility" class="col-md-4 col-form-label text-md-right">Eligibility:</label>
                          <div class="col-md-6">
                              <input type="number" id="eligibility" name="eligibility" class="form-control">
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="position" class="col-md-4 col-form-label text-md-right">Position:</label>
                          <div class="col-md-6">
                              <input type="text" id="position" name="position" class="form-control">
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="job_profile" class="col-md-4 col-form-label text-md-right">Job profile:</label>
                          <div class="col-md-6">
                              <input type="text" id="job_profile" name="job_profile" class="form-control">
                          </div>
                      </div>
                      
                      <div class="form-group row">
                          <label for="job_type" class="col-md-4 col-form-label text-md-right">Job Type:</label>
                          <div class="col-md-6">
                              <select required class="form-select" id="job_type" name="job_type">
                                  <option value="1">WFH</option>
                                  <option value="2">Full Time</option>
                                  <option value="3">Internship</option>
                              </select>
                          </div>
                      </div>

                      <div class="form-group row">
                        <label for="job_location" class="col-md-4 col-form-label text-md-right">Job location:</label>
                        <div class="col-md-6">
                            <input type="text" id="job_location" name="job_location" class="form-control">
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="date_of_joining" class="col-md-4 col-form-label text-md-right">Date of joining (YYYY-MM-DD):</label>
                          <div class="col-md-6">
                              <input type="date" id="date_of_joining" name="date_of_joining" class="form-control" required>
                          </div>
                      </div>

                      <div class="form-group row">
                          <label for="package" class="col-md-4 col-form-label text-md-right">Stipend/Package:</label>
                          <div class="col-md-6">
                              <input type="text" id="package" name="package" class="form-control">
                          </div>
                      </div>

                      <div class="form-group row d-flex justify-content-center">
                          <h4>{{message}}</h4>
                      </div>

                      
                      <div class="col-md-3 float-right">
                          <button type="submit" class="btn btn-danger">Add Drive</button>
                      </div>

                  </div>
              </form>
          </div>
      </div>
  </div>
</div>

{% endblock %}

UPMS/Homepage/templates/Drives/responses.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Responses{% endblock %}

{% block nav_sidebar %}
  {% include 'new_sidebar.html' with active="drives" %}
{% endblock %}

{% block stylesheets %}
{% include 'adminlte/lib/_styles.html' %}
  <link rel="stylesheet" href="{% static '/css/loader.css' %}">
{% endblock %}


{% block content %}
<div class="cotainer">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="card">

              <div class="card-header text-center bg-red"><h2>{{drive.name}}'s responses</h2></div>

              <div class="card-body" style="overflow-x:auto;">
                <table class="table table-inline table-hover table-striped">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Response ID</th>
                      <th scope="col">UID of applicant</th>
                      <th scope="col">Name of Applicant</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in responses %}
                    <tr>
                      <td scope="row">{{forloop.counter}}</td>
                      <td>{{i.id}}</td>
                      <td><a href="{% url 'profile' i.user.username %}">{{i.user.username}}</a></td>
                      <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                      <td class="row">
                        <div>
                          <select required class="form-select" id="gender" name="gender">
                            <option {% if i.status == 1 %} selected {% endif %} value="1">Applied</option>
                            <option {% if i.status == 2 %} selected {% endif %} value="2">Processing</option>
                            <option {% if i.status == 3 %} selected {% endif %} value="3">Shortlisted</option>
                            <option {% if i.status == 4 %} selected {% endif %} value="4">Rejected</option>
                            <option {% if i.status == 5 %} selected {% endif %} value="5">Selected</option>
                          </select>
                        </div>
                        
                        <div class="pl-4">
                          <a href="#{{i.id}}" class="text-red"><i class="fas fa-pen"></i></a>
                          <a href="#{{i.id}}" class="text-green"><i class="fas fa-check"></i></a>
                        </div>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}